<?php
foreach ($this->runners as $runner)
{
	echo $runner->firstname." ".$runner->surname." ".$runner->dateofbirth." ".$runner->status.
		"|".$runner->id."|".$runner->firstname."|".$runner->surname.
		"|".$runner->standard."|".$runner->dateofbirth."|".$runner->gender.
		"|".$runner->companyid."|".$runner->companyname.
		"|".$runner->teamid."|".$runner->teamname."|".$runner->agecat.
		"\n";
}
?>