<div class="main">		    
	<!--  top row -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center"><h3>BHAA Membership Form 2010</h3></div>
	    </div>
	</div>

<div align="center">
<p class="style2">Thank You . </p>
<p class="style2">You have now given all details needed for membership.</p>
<p class="style2">Please click on the Buy Now Icon&nbsp; below to pay your 
subscription for 2010. You can pay via PayPal or your credit card</p>
<h4>The cost is <span class="price-total">€ 15.89 EUR</span></h4>

<form target="new" action="https://www.paypal.com/cgi-bin/webscr" method="post">
<div class="style2">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="2521272">
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
<input type="image" src="https://www.paypal.com/en_US/i/btn/btn_buynowCC_LG_global.gif" border="0" name="submit" alt=""></div>
</form>
</div>
	
</div>