<div class="main">

	<!-- image -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center">
		    	<img src="http://members.bhaa.ie/images/bhaa_form_logo.png" width="100" height="100"/>
		    </div> 
	    </div>
	</div>
		    
	<!--  top row -->
	<div class="subcolumns">
	    <div class="c70l">
   		    <div class="center"><h3>BHAA Membership Renewal</h3></div>
	    </div>
	</div>

	<!-- signed -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l"><pre>
Dear <?php echo $this->escape($this->firstname);?>,

This is just a confirmation that your membership renewal has been processed for the year.

Your race results and upcoming BHAA events can be found on the website at <a href="http://bhaa.ie/members/app/runner/index/id/<?php echo $this->id;?>">http://bhaa.ie</a>

Yours in sport,
BHAA Committee.
</pre> 
</div>
	</div>	
</div> 