<center>
<?php
if($this->company->image != null)
echo sprintf("<img src='%s'/>",$this->company->image);
?>

<div align="left">
Team Name:
<?php
if($this->team->type=='C')
{
//	if($this->company->website != null)
//	{
		echo "<a href=";
		echo $this->url(
		array('controller'=>'company',
			'action'=>'listrunners',
			'company'=>$this->team->id
		));
		echo ">".$this->team->name."</a>";
//	}
//	else
//		echo sprintf("%s",$this->team->name);
}
else
	echo sprintf("%s",$this->team->name);
?>
</div>

<div align="left">
<?php
echo "Sector: <a href=";
echo $this->url(
		array('controller'=>'sector',
			'action'=>'details',
			'sector'=>$this->sector->id
		));
echo ">".$this->sector->name."</a>";
?>
</div>

<div align="left">Contact:
<?php
if($this->team->contact == null)
echo sprintf("<i>We need a contact name for this team</i>");
else
echo sprintf("%s",$this->team->firstname.' '.$this->team->surname);
?>
</div>

<div align="center"><b>Team Members</b>
<?php 
echo "<table id=\"runners\" class=\"tablesorter\">"; 
echo "<thead>\n"; 
echo "<tr>\n"; 
echo "<th>Name</th>\n";
if($this->team->type=='S')
	echo "<th>Company</th>\n";
echo "<th>Gender</th>\n";
echo "<th>Standard</th>\n";
echo "</tr>\n"; 
echo "</thead>\n";
echo "<tbody>\n"; 
?>
<?php foreach($this->members as $runner) : ?>

<?php 
echo "<tr>\n";
echo "<td><a href=";
echo $this->url(
		array('controller'=>'runner',
			'action'=>'index',
			'id'=>$runner->id
		));
echo ">".$this->escape($runner->firstname) . ' '. $this->escape($runner->surname)."</a></td>";


if($this->team->type=='S')
{
echo "<td>";
	if($runner->team != $runner->company)
	{
		echo "<a href=";
		echo $this->url(
		array('controller'=>'company',
			'action'=>'listrunners',
			'company'=>$runner->company
		));
		echo ">".$runner->name.'</a>';
	}
	else 
	{
		echo "Undefined";
	}
echo "</td>";
}
?>

<td><?php echo $this->escape($runner->gender);?></td>
<td><?php echo $this->escape($runner->standard);?></td>
<?php 
endforeach;
echo "</tbody>\n";
echo "</table>\n";
?>

<div align="center"><b>Team Results</b>

</center>