<div class="main">

	<!-- image -->

    <!--  top row -->
	<div class="subcolumns">
        <div class="c70l">
            <div class="center"><h3>BHAA '<?php echo $this->event->name ?>' Day Member Registration Form</h3></div>
            <div class="center"><p>Location: <?php echo $this->event->location?>. Date: <?php echo $this->event->date?></p></div>
        </div>
    </div>

	<!-- signed -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l"><p>
Thank you <?php echo $this->escape($this->firstname);?> for using the online pre-registration process. Please print the email you recieve and bring the
signed sheet to the race. Please see the <a href="http://bhaa.ie">http://bhaa.ie</a> website for more details.

Yours in sport,
BHAA Committee.
			</p>
   		</div>
	</div>
</div>