<center>

<div align="left">
<b>Event</b> <?php echo sprintf("%s ",$this->event->name);?>
<b>Location</b> <?php echo sprintf("%s ",$this->event->location);?>
<b>Date</b> <?php echo sprintf("%s ",date('d/m/Y',strtotime($this->event->date)));?>
</div>

<div id="tabs">
    <ul>
        <li><a href="#results">Results</a></li>
        <li><a href="#teamresults">Teams</a></li>
        <li><a href="#info">Info</a></li>
    </ul>
</div>

<div id="results">

<?php 
echo "<table id=\"races\" class=\"tablesorter\">"; 
echo "<thead>\n"; 
echo "<tr>\n"; 
echo "<th>Name</th>\n";
echo "<th>Distance</th>\n";
echo "<th>Unit</th>\n";
echo "<th>Category</th>\n";
echo "</tr>\n"; 
echo "</thead>\n";
echo "<tbody>\n"; 
?>
<?php foreach($this->races as $race) : ?>

<?php 
echo "<tr>\n";
?>
<?php 
echo "<td><a href=";
echo $this->url(
	array('controller'=>'race',
		'action'=>'results',
		'id'=>$race->id));
echo ">".$this->escape($race->name)."</a></td>"
?>
<td><?php echo $this->escape($race->distance);?></td>
<td><?php echo $this->escape($race->unit);?></td>
<td><?php echo $this->escape($race->category);?></td>
<?php 
endforeach;
echo "</tbody>\n";
echo "</table>\n";
?>
</div>

<div id="teamresults">
teamresults
</div>

<div id="info">
info
</div>

</center>