BHAA <?php echo $this->event->name." ".$this->event->type; ?> Race.

<br/>
Men X M/Km;<br/>
Men;
<?php $i=1; foreach($this->men as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
M40;
<?php $i=1; foreach($this->men40 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
M45;
<?php $i=1; foreach($this->men45 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
M50;
<?php $i=1; foreach($this->men50 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
M55;
<?php $i=1; foreach($this->men55 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
M60;
<?php $i=1; foreach($this->men60 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
M65;
<?php $i=1; foreach($this->men65 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
M70; 
<?php $i=1; foreach($this->men70 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
M75;
<?php $i=1; foreach($this->men75 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
M80;
<?php $i=1; foreach($this->men80 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
M85;
<?php $i=1; foreach($this->men85 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
Women X M/Km;<br/>
Women;
<?php $i=1; foreach($this->women as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
W40;
<?php $i=1; foreach($this->women40 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
W45;
<?php $i=1; foreach($this->women45 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
W50;
<?php $i=1; foreach($this->women50 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
W55;
<?php $i=1; foreach($this->women55 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
W60;
<?php $i=1; foreach($this->women60 as $result) :
echo $i." ".$result->position." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
W65;
<?php $i=1; foreach($this->women65 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
W70;
<?php $i=1; foreach($this->women70 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
W75;
<?php $i=1; foreach($this->women75 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
W80;
<?php $i=1; foreach($this->women80 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>

<br/>
W85;
<?php $i=1; foreach($this->women85 as $result) :
echo $i." ".substr($result->firstname,0,1)." ".$result->surname." (".$result->companyname.") ".substr($result->racetime,3,7)."; ";
$i++; endforeach;
?>
