<div class="main">		    

	<!-- signed -->
	<div class="subcolumns">
	    <div class="c70l">
   		    <div class="center"><h3><?php echo $this->escape($this->subject).' '.date('Y');?></h3></div>
	    </div>
	</div>
	<!-- signed -->
	<div class="subcolumns" style="background: white">
  		<div align="left">
<div>
Thank you <?php echo $this->escape($this->firstname);?> for using the online pre-registration process.
</div>
<!-- runireleand link -->
<div> 
You now have the option to pay online via <a target="new" href="<?php echo $this->runireland;?>">runireland.com</a> which allows LASER or credit card payment. The cost is &euro;15.90.
</div>
<div>Please see the <a href="http://www.bhaa.ie">http://www.bhaa.ie</a> website for all event details.
</div>
<div>
Yours in sport,</div>
<div>BHAA Committee.</div>

   		</div>
	</div>
		
	<table class="full">
 	<tbody>
    	<tr>
        	<th>Firstname</th>
            <td><?php echo $this->escape($this->firstname);?></td>
			<td></td>
		</tr>
		<tr>
			<th>Surname</th>
			<td><?php echo $this->escape($this->surname);?></td>
			<td></td>
		</tr>
		<tr>
			<th>Gender</th>
			<td><?php echo $this->escape($this->gender);?></td>
			<td></td>
		</tr>
		<tr>
			<th>Date of Birth</th>
			<td><?php echo $this->escape($this->dateofbirth);?></td>
            <td></td>
		</tr>
		<!-- address -->
		<tr>
			<th>Address</th>
			<td><?php echo $this->escape($this->address1);?></td>
            <td></td>
		</tr>	
		<tr>
			<th>Address</th>
			<td><?php echo $this->escape($this->address2);?></td>
            <td></td>
		</tr>
		<tr>		
			<th>Address</th>
			<td><?php echo $this->escape($this->address3);?></td>
            <td></td>
		</tr>
		
		<tr>		
			<th>Email</th>
			<td><?php echo $this->escape($this->email);?></td>
            <td></td>
		</tr>

		<tr>		
			<th>Newsletter</th>
			<td><?php echo $this->escape($this->newsletter);?></td>
            <td></td>
		</tr>

		<tr>		
			<th>Telephone</th>
			<td><?php echo $this->escape($this->mobile);?></td>
            <td></td>
		</tr>

		<tr>		
			<th>Text Alert</th>
			<td><?php echo $this->escape($this->textmessage);?></td>
            <td></td>
		</tr>

		<!--<tr>
			<th>Sector</th>
			<td><php echo $this->escape($this->sectorname);?></td>
            <td></td>
		</tr>-->
		
		<tr>		
			<th>Company</th>
			<td><?php echo $this->escape($this->companyname);?></td>
            <td></td>
		</tr>
		
        <tr>
        	<th>Volunteering</th>
			<td><?php echo $this->escape($this->volunteer);?></td>
            <td></td>
        </tr>
        
        <tr>
        	<th>Tag</th>
			<td><?php echo $this->escape($this->tag);?></td>
            <td></td>
        </tr>
        
        <!--
        <php if(isset($this->runner)) : ?>
        <tr>
			<th>Runner Number</th>
			<td><php echo $this->escape($this->runner);?></td>
			<td></td>
		</tr>
        <php endif;?>
        -->
		</tbody>
	</table>

<hr/>


<div>
<a target="new" href="<?php echo $this->runireland;?>"><img src="http://www.runireland.com/sites/www.runireland.com/themes/runirelandzen/images/topbar.jpg"></a>
</div>
<div class="" style="margin-top: 20px; padding: 0 .7em;"> 
Alternatively you can print the email you will recieve and pay &euro;15.00 at registration on the race day.
</div>

</div>