<div class="main">
	<!-- image -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center">
		    	<img src="http://members.bhaa.ie/images/bhaa_form_logo.png" width="100" height="100"/>
		    </div> 
	    </div>
    </div>
	<!--  top row -->
	<div class="subcolumns">
	    <div class="c70l">
   		    <div class="center"><h3><?php echo $this->escape($this->subject).' '.date('Y');?></h3></div>
	    </div>
	</div>
	<!-- signed -->
	<div class="subcolumns" style="background: white">
  		<div align="left">
<pre>
Thank you <?php echo $this->escape($this->firstname);?> for using the online pre-registration process. Please print this email and bring the
signed sheet to the race. Please see the <a href="http://www.bhaa.ie">http://www.bhaa.ie</a> website for more details.

Yours in sport,
BHAA Committee.
</pre>
   		</div>
	</div>	
    <div align="left" class="subcolumns" style="background: white">
	<table class="full">
 	<tbody>
    	<tr>
        	<th>Firstname</th>
            <td><?php echo $this->escape($this->firstname);?></td>
			<td></td>
		</tr>
		<tr>
			<th>Surname</th>
			<td><?php echo $this->escape($this->surname);?></td>
			<td></td>
		</tr>
		<tr>
			<th>Gender</th>
			<td><?php echo $this->escape($this->gender);?></td>
			<td></td>
		</tr>
		<tr>
			<th>Date of Birth</th>
			<td><?php echo $this->escape($this->dateofbirth);?></td>
            <td></td>
		</tr>
		<!-- address -->
		<tr>
			<th>Address</th>
			<td><?php echo $this->escape($this->address1);?></td>
            <td></td>
		</tr>	
		<tr>
			<th>Address</th>
			<td><?php echo $this->escape($this->address2);?></td>
            <td></td>
		</tr>
		<tr>		
			<th>Address</th>
			<td><?php echo $this->escape($this->address3);?></td>
            <td></td>
		</tr>		
		<tr>		
			<th>Email</th>
			<td><?php echo $this->escape($this->email);?></td>
            <td></td>
		</tr>

		<tr>		
			<th>Newsletter
            </th>
			<td><?php echo $this->escape($this->newsletter);?></td>
            <td></td>
		</tr>

		<tr>		
			<th>Telephone</th>
			<td><?php echo $this->escape($this->mobile);?></td>
            <td></td>
		</tr>
		<tr>		
			<th>Text Alert</th>
			<td><?php echo $this->escape($this->textmessage);?></td>
            <td></td>
		</tr>
		<tr>		
			<th>Company</th>
			<td><?php echo $this->escape($this->companyname);?></td>
            <td></td>
		</tr>
        <tr>
        	<th>Volunteering</th>
			<td><?php echo $this->escape($this->volunteer);?></td>
            <td></td>
        </tr>
        <tr>
        	<th>Tag</th>
			<td><?php echo $this->escape($this->tag);?></td>
            <td></td>
        </tr>
		</tbody>
	</table>
    </div>
	<!-- declaration -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
            <p>I understand that I enter the Business Houses Athletic Association (BHAA) events at my own risk and that neither BHAA Race Promoters, Sponsors or Associate Sponsors, volunteers and all other persons involved directly or indirectly in the organization and management of the Event will be held responsible for any accident suffered or injury sustained by myself from any cause whatsoever, or for any property lost, damaged, mislaid, stolen or damaged, on the course, from my person, from my property or at the changing areas or at any place. Furthermore, I hereby grant full permission to any of the foregoing to use photographs, films or recordings of the event for any legitimate purpose without payment of any royalty or fees to me. I agree to abide by all lawful instructions issued to me the orgnaisers, the stewards or by An Garda Siochana in the changing area or on the Course on the day.</p>
    		</div>
   		</div>
	</div>
	<!-- min age -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p>Entrants must be at least 18 years of age on race day.</p>
    		</div>
   		</div>
    </div>
	<!-- signed -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p>Signed	_____________________________	    Date  ______________________</p>
    		</div>
   		</div>
	</div>
</div>