<div class="main">

	<!-- image -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center">
		    	<img src="http://members.bhaa.ie/public/images/bhaa_logo.png" width="700" height="100"/>
		    </div> 
	    </div>
	</div>
		    
	<!--  top row -->
	<div class="subcolumns">
	    <div class="c70l">
   		    <div class="center"><h3>BHAA Membership Application Form</h3></div>
	    </div>
	</div>

	<!-- signed -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l"><p>
			Thank you for using the online pre-registration process. Please print this email and bring the 
			signed sheet to the race. Please see the <a href="http://bhaa.ie">http://bhaa.ie</a> website for more details.
			
			Yours in sport,
			BHAA Committee.
			</p> 
   		</div>
	</div>	
	
	<table class="full">
 	<tbody>
    	<tr>
        	<th>Firstname</th>
            <td><?php echo $this->escape($this->firstname);?></td>
			<td></td>
		</tr>
		<tr>
			<th>Surname</th>
			<td><?php echo $this->escape($this->surname);?></td>
			<td></td>
		</tr>
		<tr>
			<th>Gender</th>
			<td><?php echo $this->escape($this->gender);?></td>
			<td></td>
		</tr>
		<!--<tr>
			<th>Membership Number</th>
			<td><php echo $this->escape($this->runner);?></td>
			<td></td>
		</tr>-->
		<tr>
			<th>Date of Birth</th>
			<td><?php echo $this->escape($this->dateofbirth);?></td>
            <td></td>
		</tr>
		<!-- address -->
		<tr>
			<th>Address</th>
			<td><?php echo $this->escape($this->address1);?></td>
            <td></td>
		</tr>	
		<tr>
			<th>Address</th>
			<td><?php echo $this->escape($this->address2);?></td>
            <td></td>
		</tr>
		<tr>		
			<th>Address</th>
			<td><?php echo $this->escape($this->address3);?></td>
            <td></td>
		</tr>
		
		<tr>		
			<th>Email</th>
			<td><?php echo $this->escape($this->email);?></td>
            <td></td>
		</tr>

		<tr>		
			<th>Newsletter</th>
			<td><?php echo $this->escape($this->newsletter);?></td>
            <td></td>
		</tr>

		<tr>		
			<th>Telephone</th>
			<td><?php echo $this->escape($this->mobile);?></td>
            <td></td>
		</tr>

		<tr>		
			<th>Text Alert</th>
			<td><?php echo $this->escape($this->textmessage);?></td>
            <td></td>
		</tr>

		<!--<tr>
			<th>Sector</th>
			<td><php echo $this->escape($this->sectorname);?></td>
            <td></td>
		</tr>-->
		
		<tr>		
			<th>Company</th>
			<td><?php echo $this->escape($this->companyname);?></td>
            <td></td>
		</tr>
		
        <tr>
        	<th>Volunteering</th>
			<td><?php echo $this->escape($this->volunteer);?></td>
            <td></td>
        </tr>
        
		</tbody>
	</table>
	
		<!-- declaration -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p><b>Declaration:</b> I understand that I enter Business Houses Athletic Association events at my own risk and that neither BHAA Race Promoters, Sponsors or Associate Sponsors will be held responsible for any accidents suffered or injury sustained by myself from any cause whatsoever or for any property lost, mislaid or stolen on the course or at the changing areas. Furthermore, I hereby grant full permission to any of the foregoing to use photographs, films or recordings of the events for any legitimate purpose.</p>
    		</div>
   		</div>
	</div>

	<!-- min age -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p>Entrants must be at least 18 years of age on race day.</p>
    		</div>
   		</div>
	</div>	

	<!-- signed -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p>Signed	_____________________________	    Date  ______________________</p>
    		</div>
   		</div>
	</div>
</div> 