<div class="main">
	<!-- image -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center">
		    	<img src="http://members.bhaa.ie/public/images/bhaa_logo.png" width="700" height="100"/>
		    </div> 
	    </div>
	</div>
		    
	<!--  top row -->
	<div class="subcolumns">
	    <div class="c70l">
   		    <div class="center"><h3>BHAA Membership Application Form</h3></div>
	    </div>
	</div>

	<!-- signed -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l"><pre>
Hello <?php echo $this->escape($this->firstname);?>,
  
In order to ease the registration process and ensure that our saved information is correct, we are sending you 
this online renewal form. If you can confirm the details are correct and hit the submit button it would be great.
Payment can be made online or at the next race.
  
<a href="http://members.bhaa.ie/public/membership/renew/code/<?php echo $this->escape($this->code);?>"><?php echo $this->escape($this->firstname);?> <?php echo $this->escape($this->surname);?> Renewal</a>

Yours in sport,
The BHAA Committee.
			</pre> 
   		</div>
	</div>			
</div> 