<div class="main">

	<!-- image -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center"><img src="/public/images/bhaa_form_logo.png" width="80" height="80"/></div> 
	    </div>
	</div>
		    
	<!--  top row -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center"><h3>BHAA Membership Renewal Form 2010</h3></div>
	    </div>
	</div>
	
	<?php echo $this->form;?>
	
</div>