<div class="main">

	<!-- image -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center"><img src="/public/images/bhaa_form_logo.png" width="80" height="80"/></div>
	    </div>
	</div>

   	<div class="subcolumns">
	    <div class="c70l">
		    
			<div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;"> 
			<p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
			The online membership form is temporally disabled while we process applications before the next BHAA event.
			<strong>Note:</strong>New and day members can register on the day at the event HQ.</p>
			</div>
		</div>
	</div>
</div>