<div id="gmap" align="left">
        <iframe width="600" height="500" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
        src="http://www.google.com/maps/ms?ie=UTF8&amp;msa=0&amp;msid=110398891020944036591.000462e322a4a6111a4f7&amp;ll=53.371191,-6.389193&amp;spn=0.189268,0.426493&amp;output=embed">
        </iframe><br /><small>View <a href="http://www.google.com/maps/ms?ie=UTF8&amp;msa=0&amp;msid=110398891020944036591.000462e322a4a6111a4f7&amp;ll=53.371191,-6.389193&amp;spn=0.189268,0.426493&amp;source=embed"
        style="color:#0000FF;text-align:left">BHAA Race Locations</a> in a larger map</small>
</div>