<center>

<div align="center">
<?php
if($this->company->image != null)
echo sprintf('<img alt="%s" src="%s"/>',$this->company->name,$this->company->image);
?>
</div>
<br/>
<div align="left">Company
<?php
if($this->company->website != null)
echo sprintf(" Website : <a target='_new' href='%s'>%s</a>",$this->escape($this->company->website),$this->company->name);
else
echo sprintf("%s",$this->company->name);
?>
</div>
<div align="left">
<?php
echo 'Sector <a href="';
echo $this->url(
		array('controller'=>'houses',
			'action'=>'sector',
			'id'=>$this->sector->id
		));
echo '">'.htmlentities($this->sector->name)."</a>";
?>
</div>

<div align="left">
<?php
if(!empty($this->leaguesummary))
    echo 'League Summary : Division '.$this->leaguesummary->leaguedivision.' Position '.$this->leaguesummary->leagueposition;
?>
</div>

<br/>

<?php if($this->user) : ?>
<div class="ui-widget" align="left">
<div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;">
<span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>
<?php
echo '<strong><a href="';
echo $this->url(
	array('controller'=>'company',
			'action'=>'addraceorganiserpoints',
			'id'=>$this->company->id));
echo '">Add Team Race Organiser Points</a></strong>';
?>
</div></div>
<?php endif; ?>

<div class="yui-g">
    <div class="yui-u first">
        <div align="left"><b><?php echo $this->company->name; ?> Runners</b></div>
<div>
<?php
echo "<table class=\"tablesorter\">";
echo "<thead>\n";
echo "<tr>\n";
echo "<th>Name</th>\n";
echo "<th>Gender</th>\n";
echo "<th>Standard</th>\n";
echo "<th>Races</th>\n";
echo "</tr>\n";
echo "</thead>\n";
echo "<tbody>\n";
?>
<?php foreach($this->runners as $runner) : ?>

<tr>
<?php
echo '<td><a href="';
echo $this->url(
		array('controller'=>'runner',
			'action'=>'index',
			'id'=>$runner->id
		),null,true);
echo '">'.$this->escape($runner->firstname) . ' '. $this->escape($runner->surname)."</a></td>";
?>
<td><?php echo $this->escape($runner->gender);?></td>
<td><?php echo $this->escape($runner->standard);?></td>
<td><?php echo $this->escape($runner->races);?></td>
</tr>
<?php
endforeach;
echo "</tbody>\n";
echo "</table>\n";
?>
</div>

	</div>
   	<div class="yui-u">
            <div align="left"><b><?php echo $this->company->name; ?> individual league positions.</b></div>
            <?php echo $this->individualLeagueSummaryHelper($this->indivLeague,false); ?>
        </div>
</div>

<div>
<div align="left"><b><?php echo $this->company->name; ?> team results.</b></div>
<?php echo $this->teamResultTable();?>
</div>

</center>