<center>

<div align="left">
<?php
echo "Sector: <a href=";
echo $this->url(
		array('controller'=>'houses',
			'action'=>'sector',
			'id'=>$this->sector->id
		),null,true);
echo ">".$this->sector->name."</a>";
?>
</div>

<div align="left">
Team Name : <?php echo $this->team->name ?>
</div>

<div align="left">Contact:
<?php
if($this->team->contact == null)
echo sprintf("<i>We need a contact name for this team</i>");
else
echo sprintf("%s",$this->team->firstname.' '.$this->team->surname);
?>
</div>

<div align="left">
<?php
if(!empty($this->leaguesummary))
    echo 'League Summary : Division '.$this->leaguesummary->leaguedivision.' Position '.$this->leaguesummary->leagueposition;
?>
</div>

<br/>
<div class="yui-g">
    <div class="yui-u first">
        <div align="left"><b>Runners with <?php echo $this->team->name; ?></b></div>
<?php
echo "<table id=\"teammembers\" class=\"tablesorter\">";
echo "<thead>\n";
echo "<tr>\n";
echo "<th>Name</th>\n";
if($this->team->type=='S')
    echo "<th>Company</th>\n";

echo "</tr>\n";
echo "</thead>\n";
echo "<tbody>\n";
?>
<?php foreach($this->members as $runner) : ?>

<?php
echo "<tr>\n";
echo "<td><a href=";
echo $this->url(
		array('controller'=>'runner',
			'action'=>'index',
			'id'=>$runner->id
		));
echo ">".$this->escape($runner->firstname) . ' '. $this->escape($runner->surname)."</a></td>";


if($this->team->type=='S')
{
echo "<td>";
	if($runner->team != $runner->company)
	{
		echo "<a href=";
		echo $this->url(
		array('controller'=>'houses',
			'action'=>'company',
			'id'=>$runner->company
		));
		echo ">".$runner->name.'</a>';
	}
	else
	{
		echo "Undefined";
	}
echo "</td>";
}
?>
<?php
endforeach;
echo "</tbody>\n";
echo "</table>\n";
?>

    </div>
    <div class="yui-u">
        <div align="left"><b><?php echo $this->team->name; ?> individual league positions.</b></div>
        <?php echo $this->individualLeagueSummaryHelper($this->indivLeague,false); ?>
    </div>
</div>

<div align="center"><b>Team Results</b></div>

<table id="teamresults" class="tablesorter">
<thead>
<tr>
<th>Name</th>
<th>Points Total</th>
<th>First</th>
<th>Second</th>
<th>Third</th>
<th>Standard Total</th>
<th>Class</th>
</tr>
</thead>
<tbody>
<?php foreach($this->teamresults as $result) : ?>
<tr>
<td>
<?php
echo "<a href=";
echo $this->url(
		array('controller'=>'event',
			'action'=>'index',
			'tag'=>$result->tag
		));
echo ">".$this->escape($result->tag)."</a>";?></td>
<td><?php echo $this->escape($result->positiontotal);?></td>
<td><?php
echo "<a href=";
echo $this->url(
		array('controller'=>'runner',
			'action'=>'index',
			'id'=>$result->runnerfirst
		));
echo ">".$this->escape($result->r1sn)."</a>";?></td>
<td><?php
echo "<a href=";
echo $this->url(
		array('controller'=>'runner',
			'action'=>'index',
			'id'=>$result->runnersecond
		));
echo ">".$this->escape($result->r2sn)."</a>";?></td>
<td><?php
echo "<a href=";
echo $this->url(
		array('controller'=>'runner',
			'action'=>'index',
			'id'=>$result->runnerthird
		));
echo ">".$this->escape($result->r3sn)."</a>";?></td>
<td><?php echo $this->escape($result->standardtotal);?></td>
<td><?php echo $this->escape($result->class);?></td>
<?php
endforeach;
?>
</tbody>
</table>
</center>