
<form action="/registration/process" method="post">

<div class="main">

	<!-- image -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center"><img src="/public/images/bhaa_form_logo.png" width="80" height="80"/></div> 
	    </div>
	</div>
		    
	<!--  top row -->
	<div class="subcolumns">

	    <div class="c70l">
		    <div class="float_left">Fees?</div> 
		    <div class="center"><h3>BHAA Membership Form</h3></div> 
			<div class="float_right">Race Number?</div> 
			<div class="float_right">renewal?</div> 
	    </div>

	</div>

	<!-- name row -->
	<div class="subcolumns">
  		<div class="c70l">
			<div id="x">
				<label class="column">Name : </label> 
				<input class="myBox" type="text" size="30" name="firstname" title="firstname"/>
				<input class="myBox" type="text" size="30" name="surname"  title="surname"/>
				<div class="float_right">
					<label class="column">Gender:</label> 
					<select name="gender"> 
						<option value="blank"></option> 
						<option value="male">Male</option> 
						<option value="female">Female</option> 
					</select>
				</div>
			</div>
  		</div>
	</div>

	<!-- member address row -->
	<div class="subcolumns">
  		<div class="c70l">
			<div id="x">
				<label class="column">Address : </label> 
				<input class="myBox" type="text" size="30" name="firstname" title="firstname"/>
				<input class="myBox" type="text" size="30" name="surname"  title="surname"/>
				<div class="float_right">
					<label class="column">Date of Birth:</label> 
					<input class="myBox" type="text" size="30" name="surname"  title="surname"/>
				</div>
			</div>
  		</div>
	</div>
	
	<!-- email/mobile -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
  			<div>
				<label class="column">E-mail Address</label>
		   		<input class="myBox" type="text" size="10" name="name"/>
				<div class="float_right">
				    <label>Telephone</label>
		    		<input class="myBox" type="text" size="10" name="name"/>
		  		</div>
		  	</div>
  		</div>
	</div>
        
	<!-- company name -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
  			<div>
				<label class="column">Company Name</label>
		   		<input class="myBox" type="text" size="10" name="name"/>
		   
				    <label>Sector</label>
		    		<input class="myBox" type="text" size="10" name="name"/>
		  		<div class="float_right">
				    <label>Work Telephone</label>
		    		<input class="myBox" type="text" size="10" name="name"/>
		  		</div>
		  	</div>
  		</div>
	</div>
	
	<!-- registration -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p><b>Day Registration Fee : €?.00 per member.</b></p>
    		</div>
   		</div>
	</div>
	
	<!-- declaration -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p><b>Declaration:</b> I understand that I enter Business Houses Athletic Association events at my own risk and that neither BHAA Race Promoters, Sponsors or Associate Sponsors will be held responsible for any accidents suffered or injury sustained by myself from any cause whatsoever or for any property lost, mislaid or stolen on the course or at the changing areas. Furthermore, I hereby grant full permission to any of the foregoing to use photographs, films or recordings of the events for any legitimate purpose.</p>
    		</div>
   		</div>
	</div>

	<!-- min age -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p>Entrants must be at least 18 years of age on race day.</p>
    		</div>
   		</div>
	</div>	

	<!-- fees -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p>Total Fees Enclosed; €______ (Cheques & Postal Orders should be made payable to BHAA)</p>
    		</div>
   		</div>
	</div>	

	<!-- signed -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p>Signed	_____________________________	    Date  ______________________</p>
    		</div>
   		</div>
	</div>	

	<!-- contact details -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p>
    			RETURN COMPLETED ENTRY FORM TO Registrar, BHAA Office, Donore Harriers, Chapelozid, Dublin 20
Telephone Number (01)  6263746		Fax Number   (01)  6263757</p>
    		</div>
   		</div>
	</div>
          
   	<!-- renewal date -->
	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="float_left">
    			<p>BHAA Membership Renewal Date 31st January 2010</p>
    		</div>
   		</div>
	</div>                                                                       

	<div class="subcolumns" style="background: white">
  		<div class="c70l">
			<div class="center">
    			    <input type="submit"/>
    		</div>
   		</div>
	</div>     
	
</div> 
</form>