<div class="center"><h3>BHAA '<?php echo $this->event->name ?>' Registration Form</h3></div>
<div class="center"><p>Location: <?php echo $this->event->location?>. Date: <?php echo $this->event->date?></p></div>
<div>
<?php 
echo "<table class=\"tablesorter\">"; 
echo "<thead>\n"; 
echo "<tr>\n"; 
echo "<th>Name</th>\n";
echo "<th>Gender</th>\n";
echo "<th>BHAA Number</th>\n";
echo "</tr>\n"; 
echo "</thead>\n";
echo "<tbody>\n"; 
?>
<?php foreach($this->registered as $runner) : ?>
<tr>
<td><?php echo $this->escape($runner->firstname);?> <?php echo $this->escape($runner->surname);?></td>
<td><?php echo $this->escape($runner->gender);?></td>
<td><?php echo $this->escape($runner->runner);?></td>
</tr>
<?php 
endforeach;
echo "</tbody>\n";
echo "</table>\n";
?>
</div>