
<div align="left">

	<!-- image -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center"><img src="/public/images/bhaa_form_logo.png" width="80" height="80"/></div> 
	    </div>
	</div>
		    
	<!--  top row -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center"><h3>BHAA '<?php echo $this->event->name ?>' Registration Form</h3></div>
		    <div class="center"><p>Location: <?php echo $this->event->location?>. Date: <?php echo $this->event->date?></p></div>
	    </div>
	</div>

	<?php echo $this->form;?>

</div>