<form action="./preregistration" method="post">

<!--				
http://monzee.wordpress.com/2009/02/23/decorators-are-hard-lets-go-shopping/
http://framework.zend.com/manual/en/zend.form.standardDecorators.html#zend.form.standardDecorators.viewScript
-->
<!--				<label class="column">Name : </label> -->
 <table class="full">
 	<tbody>
    	<tr>
        	<th><?php echo $this->element->firstname->renderLabel();?></th>
            <td><?php echo $this->element->firstname->renderElem();?></td>
			<td><?php echo $this->element->firstname->renderErrors();?></td>
		</tr>
		<tr>
			<th><?php echo $this->element->surname->renderLabel();?></th>
			<td><?php echo $this->element->surname->renderElem();?></td>
			<td><?php echo $this->element->surname->renderErrors();?></td>
		</tr>
		<tr>
			<th><?php echo $this->element->gender->renderLabel();?></th>
			<td><?php echo $this->element->gender->renderElem();?></td>
			<td><?php echo $this->element->gender->renderErrors();?></td>
		</tr>
		<tr>
			<th><?php echo $this->element->dateofbirth->renderLabel();?></th>
			<td><?php echo $this->element->dateofbirth->renderElem();?></td>
            <td><?php echo $this->element->dateofbirth->renderErrors();?></td>
		</tr>

		<!--<php echo $this->element->membershipnumber->renderElem();?>-->

		<!-- address -->
		<tr>
			<th><?php echo $this->element->address1->renderLabel();?></th>
			<td><?php echo $this->element->address1->renderElem();?></td>
			<td><?php echo $this->element->address1->renderErrors();?></td>
		</tr>
		<tr>
			<th><?php echo $this->element->address2->renderLabel();?></th>
			<td><?php echo $this->element->address2->renderElem();?></td>
			<td><?php echo $this->element->address2->renderErrors();?></td>
		</tr>
		<tr>
			<th><?php echo $this->element->address3->renderLabel();?></th>
			<td><?php echo $this->element->address3->renderElem();?></td>
			<td><?php echo $this->element->address3->renderErrors();?></td>
		</tr>

		<tr>
			<th><?php echo $this->element->email->renderLabel();?></th>
			<td><?php echo $this->element->email->renderElem();?> <?php echo $this->element->email->renderErrors();?></td>
        </tr>

        <tr>
			<th><?php echo $this->element->newsletter->renderLabel();?></th>
			<td><?php echo $this->element->newsletter->renderElem();?> <?php echo $this->element->newsletter->renderErrors();?></td>
		</tr>

		<tr>
			<th><?php echo $this->element->mobile->renderLabel();?></th>
			<td><?php echo $this->element->mobile->renderElem();?> <?php echo $this->element->mobile->renderErrors();?></td>
        </tr>

        <tr>
			<th><?php echo $this->element->textmessage->renderLabel();?></th>
			<td><?php echo $this->element->textmessage->renderElem();?> <?php echo $this->element->textmessage->renderErrors();?></td>
		</tr>

        <tr>
            <th><?php echo $this->element->companyname->renderLabel();?></th>
            <td><?php echo $this->element->companyname->renderElem();?> <?php echo $this->element->companyname->renderErrors();?> <?php echo $this->element->company->renderElem();?> [Enter first three letters to search for an existing BHAA company.]</td>
        </tr>

        <tr>
        	<th>Declaration</th>
        	<td>I understand that I enter Business Houses Athletic Association (BHAA) events at my own risk and that neither BHAA Race Promoters, Sponsors or Associate Sponsors will be held responsible for any accidents suffered or injury sustained by myself from any cause whatsoever or for any property lost, mislaid or stolen on the course or at the changing areas. Furthermore, I hereby grant full permission to any of the foregoing to use photographs, films or recordings of the events for any legitimate purpose.</td>
        	<td></td>
        </tr>

        <tr>
        	<th></th>
        	<td>Entrants must be at least 18 years of age on race day.</td>
        	<td></td>
        </tr>

        <?php echo $this->element->eventid->renderElem();?>

        <tr>
        	<th></th>
        	<td align="center"><input type="submit" value="BHAA Day Membership Pre-register"/></td>
        	<td></td>
        </tr>

	</tbody>
</table>

</form>