<div class="main">

    <!--  top row -->
    <div class="subcolumns">
        <div class="c70l">
            <div class="center"><h3>BHAA '<?php echo $this->event->name ?>' Day Member Registration Form</h3></div>
            <div class="center"><p>Location: <?php echo $this->event->location?>. Date: <?php echo $this->event->date?></p></div>
        </div>
    </div>

	<?php echo $this->form;?>

</div>