<div class="main">
	<!-- image -->
	<div class="subcolumns">
	    <div class="c70l">
		    <div class="center">
		    	<img src="http://members.bhaa.ie/public/images/bhaa_form_logo.png" width="100" height="100"/>
		    </div> 
	    </div>
    </div>
	<!--  top row -->
	<div class="subcolumns">
	    <div class="c70l">
   		    <div class="center"><h3>BHAA Membership Application <?php echo date('Y');?></h3></div>
	    </div>
	</div>
	<!-- signed -->
	<div class="subcolumns" style="background: white">
  		<div align="left">
<pre>
Thank you <?php echo $this->escape($this->firstname);?> for using the online registration form.

Your BHAA membership number is <?php echo $this->id; ?>

Your personal results page is :  <a href="<?php echo sprintf('http://bhaa.ie/members/app/runner/index/id/%d',$this->id);?>"><?php echo sprintf('http://bhaa.ie/members/app/runner/index/id/%d',$this->id);?></a>

See you at the next race.

Yours in sport,
BHAA Committee.
</pre>
   		</div>
    </div>
</div>